gateway_app:
  host: "0.0.0.0"
  external_ip: "158.160.131.145"
  port: 8080
  port_external: 80
  prefix: "/api/v1"
  log_level: "info"
  reload: True

  reservation_serv_host: "reservation-service"
  reservation_serv_port: 8070

  payment_serv_host: "payment-service"
  payment_serv_port: 8060

  loyalty_serv_host: "loyalty-service"
  loyalty_serv_port: 8050
