name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install the necessary packages
        run: pip3.10 install -r services/gateway_service/requirements.txt

      - name: Run unit tests for loyalty service
        run: pytest -vs services/loyalty_service/app/unit_tests/tests.py
  
  docker-hub:
    name: Push docker hub
    runs-on: ubuntu-latest
    strategy:
	  matrix:
		include:
		  - image: ./services/gateway_service
		    dockerfile: gateway_service/Dockerfile
		  - image: ./services/loyalty_service
		    dockerfile: loyalty_service/Dockerfile
          - image: ./services/payment_service
		    dockerfile: payment_service/Dockerfile
          - image: ./services/reservation_service
		    dockerfile: reservation_service/Dockerfile
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Docker Hub login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.dockerfile }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
  
  deploy:
    name: Deploy service on VM
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Send project files on VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "services,scripts,Dockerfile,docker-compose.yml"
          target: /home/${{ secrets.SSH_USER }}/hotel_booking_system
      
      - name: Build and up hotel-booking-system
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/hotel_booking_system
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi payment_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi loyalty_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi reservation_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose build
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
            echo ${{ secrets.SSH_PASSWORD }} | sudo ./scripts/wait-script.sh
  
  api-test:
    name: Run API Tests
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 15
          reporters: '[ "cli" ]'
          
      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true